apiVersion: v1
kind: Service
metadata:
  name: micro-agent-api-service
  namespace: micro-agent-platform
  labels:
    app.kubernetes.io/name: micro-agent-api
    app.kubernetes.io/component: api
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: micro-agent-platform
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS EKS
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "my-resource-group"  # For AKS
    cloud.google.com/load-balancer-type: "External"  # For GKE
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: micro-agent-api
    app.kubernetes.io/component: api
  sessionAffinity: None
  externalTrafficPolicy: Cluster

---
apiVersion: v1
kind: Service
metadata:
  name: micro-agent-redis-service
  namespace: micro-agent-platform
  labels:
    app.kubernetes.io/name: micro-agent-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/version: "7.0"
    app.kubernetes.io/part-of: micro-agent-platform
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    app.kubernetes.io/name: micro-agent-redis
    app.kubernetes.io/component: cache
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: micro-agent-platform
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/version: "2.40"
spec:
  type: ClusterIP
  ports:
    - name: prometheus
      port: 9090
      targetPort: prometheus
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: micro-agent-platform
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/version: "9.5"
spec:
  type: LoadBalancer
  ports:
    - name: grafana
      port: 80
      targetPort: grafana
      protocol: TCP
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring